import React, { useState } from 'react';
import { SessionInsights } from '../types';
import {
  X,
  Sparkles,
  CheckCircle2,
  Lightbulb,
  HeartHandshake,
  Copy,
  Check,
  Download,
  ArrowRight,
} from 'lucide-react';

interface SessionSummaryModalProps {
  insights: SessionInsights | null;
  isLoading: boolean;
  isOpen: boolean;
  onClose: () => void;
  entryTitle?: string;
  onSelectSuggestedPrompt?: (prompt: string) => void;
}

export const SessionSummaryModal: React.FC<SessionSummaryModalProps> = ({
  insights,
  isLoading,
  isOpen,
  onClose,
  entryTitle,
  onSelectSuggestedPrompt,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopySummary = () => {
    if (!insights) return;
    const text = `MindHaven Session Summary: ${entryTitle || 'Reflection'}
    
Summary:
${insights.summary}

Mood Analysis:
${insights.moodAnalysis}

Key Realizations:
${insights.keyInsights.map((i) => `• ${i}`).join('\n')}

Action Steps:
${insights.actionSteps.map((a) => `[ ] ${a}`).join('\n')}
`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!insights) return;
    const markdown = `# MindHaven AI Session Insights: ${entryTitle || 'Reflection'}
*Date: ${new Date().toLocaleDateString()}*

## 📝 Session Summary
${insights.summary}

## 🌿 Mood & Emotional Analysis
${insights.moodAnalysis}

## 💡 Key Realizations
${insights.keyInsights.map((i) => `- ${i}`).join('\n')}

## 🎯 Action Steps & Takeaways
${insights.actionSteps.map((a) => `- [ ] ${a}`).join('\n')}

${insights.suggestedPromptForNextTime ? `\n## 🔮 Suggested Next Reflection\n"${insights.suggestedPromptForNextTime}"` : ''}
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MindHaven_Summary_${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-stone-900/60 backdrop-blur-xs z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
      <div
        className="w-full max-w-2xl bg-white dark:bg-stone-900 rounded-3xl border border-stone-200 dark:border-stone-800 shadow-2xl overflow-hidden flex flex-col my-auto max-h-[90vh] transition-all animate-in fade-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="p-6 border-b border-stone-200/80 dark:border-stone-800 flex items-center justify-between bg-gradient-to-r from-emerald-50/50 via-amber-50/30 to-stone-50 dark:from-emerald-950/30 dark:via-stone-900 dark:to-stone-900">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center shadow-md">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-serif font-bold text-xl text-stone-900 dark:text-stone-50">
                AI Session Insights & Action Plan
              </h2>
              <p className="text-xs text-stone-500 dark:text-stone-400">
                Generated by Gemini 3.6 Flash from your reflection session
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-stone-400 hover:text-stone-600 dark:hover:text-stone-200 hover:bg-stone-100 dark:hover:bg-stone-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Content */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 text-stone-800 dark:text-stone-200 text-sm">
          {isLoading ? (
            <div className="py-16 text-center space-y-4">
              <div className="w-12 h-12 mx-auto border-3 border-emerald-600 border-t-transparent rounded-full animate-spin"></div>
              <p className="font-serif font-medium text-stone-700 dark:text-stone-300">
                Gemini is analyzing your reflection session...
              </p>
              <p className="text-xs text-stone-400">
                Extracting key realizations, emotional context, and action steps.
              </p>
            </div>
          ) : !insights ? (
            <div className="py-12 text-center text-stone-500">
              <p>No insights generated yet. Write a few reflection messages and click "Generate AI Insights".</p>
            </div>
          ) : (
            <>
              {/* Summary Section */}
              <div className="p-4 rounded-2xl bg-stone-50 dark:bg-stone-800/60 border border-stone-200/80 dark:border-stone-700/60">
                <h3 className="font-serif font-semibold text-stone-900 dark:text-stone-100 mb-2 flex items-center gap-2 text-base">
                  <Sparkles className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                  <span>Session Summary</span>
                </h3>
                <p className="text-stone-600 dark:text-stone-300 leading-relaxed font-sans">
                  {insights.summary}
                </p>
              </div>

              {/* Mood Analysis Section */}
              <div className="p-4 rounded-2xl bg-amber-50/60 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-800/40">
                <h3 className="font-serif font-semibold text-amber-900 dark:text-amber-200 mb-2 flex items-center gap-2 text-base">
                  <HeartHandshake className="w-4 h-4 text-amber-600 dark:text-amber-400" />
                  <span>Emotional & Mood Theme</span>
                </h3>
                <p className="text-amber-900/90 dark:text-amber-300/90 leading-relaxed">
                  {insights.moodAnalysis}
                </p>
              </div>

              {/* Key Realizations */}
              <div>
                <h3 className="font-serif font-semibold text-stone-900 dark:text-stone-100 mb-3 flex items-center gap-2 text-base">
                  <Lightbulb className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                  <span>Key Realizations & Insights</span>
                </h3>
                <ul className="space-y-2">
                  {insights.keyInsights.map((insight, idx) => (
                    <li
                      key={idx}
                      className="p-3 rounded-xl bg-white dark:bg-stone-800 border border-stone-200/80 dark:border-stone-700/80 flex items-start gap-3 shadow-2xs"
                    >
                      <div className="w-5 h-5 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                        {idx + 1}
                      </div>
                      <span className="text-stone-700 dark:text-stone-200 leading-snug">
                        {insight}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Action Steps */}
              <div>
                <h3 className="font-serif font-semibold text-stone-900 dark:text-stone-100 mb-3 flex items-center gap-2 text-base">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                  <span>Action Steps & Gentle Commitments</span>
                </h3>
                <ul className="space-y-2">
                  {insights.actionSteps.map((step, idx) => (
                    <li
                      key={idx}
                      className="p-3 rounded-xl bg-emerald-50/40 dark:bg-emerald-950/20 border border-emerald-200/60 dark:border-emerald-800/40 flex items-start gap-3"
                    >
                      <input
                        type="checkbox"
                        className="mt-1 rounded text-emerald-600 focus:ring-emerald-500 cursor-pointer"
                      />
                      <span className="text-stone-800 dark:text-stone-200 leading-snug">
                        {step}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Next Suggested Prompt */}
              {insights.suggestedPromptForNextTime && (
                <div className="p-4 rounded-2xl bg-indigo-50/60 dark:bg-indigo-950/30 border border-indigo-200/60 dark:border-indigo-800/40 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                  <div>
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-indigo-700 dark:text-indigo-300">
                      Suggested for next time:
                    </span>
                    <p className="text-sm font-serif italic text-indigo-900 dark:text-indigo-200 mt-0.5">
                      "{insights.suggestedPromptForNextTime}"
                    </p>
                  </div>

                  {onSelectSuggestedPrompt && (
                    <button
                      onClick={() => {
                        onSelectSuggestedPrompt(insights.suggestedPromptForNextTime!);
                        onClose();
                      }}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-medium transition cursor-pointer flex-shrink-0"
                    >
                      <span>Use Prompt</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>
              )}
            </>
          )}
        </div>

        {/* Modal Footer Actions */}
        {insights && !isLoading && (
          <div className="p-4 border-t border-stone-200/80 dark:border-stone-800 bg-stone-50/80 dark:bg-stone-900/80 flex items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <button
                onClick={handleCopySummary}
                className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-white dark:bg-stone-800 border border-stone-200 dark:border-stone-700 text-stone-700 dark:text-stone-300 hover:bg-stone-100 dark:hover:bg-stone-700 text-xs font-medium transition cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy Summary'}</span>
              </button>

              <button
                onClick={handleDownloadMarkdown}
                className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-white dark:bg-stone-800 border border-stone-200 dark:border-stone-700 text-stone-700 dark:text-stone-300 hover:bg-stone-100 dark:hover:bg-stone-700 text-xs font-medium transition cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .md</span>
              </button>
            </div>

            <button
              onClick={onClose}
              className="px-5 py-2 rounded-xl bg-stone-900 hover:bg-stone-800 dark:bg-stone-100 dark:hover:bg-white text-white dark:text-stone-900 font-medium text-xs transition cursor-pointer"
            >
              Close
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
